SalesforceData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Open_Sales_Order__c</fullName>
        <label>Open Sales Order</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Details__c</fullName>
        <label>Owner Details</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

SalesforceData/src/objects/EFT_Transaction_Status__c.object
<CustomObject>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>EFT Transaction Status</label>
    <nameField>
        <label>EFT Transaction Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Transaction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceData/src/objects/SalesHeader__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Customer__c</fullName>
        <label>Bill To Customer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_to_City__c</fullName>
        <label>Bill to City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bill_to_Postal_Code__c</fullName>
        <label>Bill to Postal Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_to_State__c</fullName>
        <label>Bill to State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_to_Street__c</fullName>
        <label>Bill to Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EFT_Transaction_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EFT Transaction Status</label>
        <referenceTo>EFT_Transaction_Status__c</referenceTo>
        <relationshipLabel>SalesHeader</relationshipLabel>
        <relationshipName>SalesHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>S_Lookup_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lookup Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesHeader</relationshipLabel>
        <relationshipName>SalesHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>S_lookup_contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact lookup</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SalesHeader</relationshipLabel>
        <relationshipName>SalesHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>Ship to City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Postal_Code__c</fullName>
        <label>Ship to Postal Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>Ship to State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Street__c</fullName>
        <label>Ship to Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SalesHeader</label>
    <nameField>
        <label>SalesHeader Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesHeader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceData/src/classes/SalesheaderCaseTestClass.cls
@isTest
public class SalesheaderCaseTestClass
{
     public static testMethod void  SalesHeaderTestMethod()
    {
       /* Date d = Date.parse(8/22/2016);
        EFT_Transaction_Status__c EFT = new EFT_Transaction_Status__c(Name='EFT5',
        Transaction_Date__c=d ,Transaction_Status__c='Open');
        
        insert e;
        
        Contact con = new Contact();
        con.
        insert con;
        
        Account A =new Account(Name='Account5');
        insert A; */
        
        
        
        SalesHeader__c SHeader = new SalesHeader__c(
        Name='Sales5',
        Bill_to_City__c='Nagpur',
        Bill_To_Customer__c='Disha',
        Bill_to_Postal_Code__c=445566,
        Bill_to_State__c='MS',
        Bill_to_Street__c='Wardhaman',
        Ship_to_City__c='Gondia',
        Ship_to_Postal_Code__c=667788,
        Ship_to_State__c='MP',
        Ship_to_Street__c='Murri',
        Status__c='Open',
        Total_Amount__c=70000,
        Transaction_Status__c='Open',
        S_lookup_contact__c='0032800000YQ0Up',
        EFT_Transaction_Status__c='a0W28000004u17m',
        S_Lookup_Account__c='0012800000nsMcX'
        
        );
        Test.StartTest();
        insert SHeader;
        Test.StopTest();
        List<Case> c = new   List<Case>([Select id,Owner_Details__c,CaseNumber, Priority,Open_Sales_Order__c,Order_Date__c,Sales_Order_Number__c,Type From Case]);
        //system.assertEquals(c.size(),1);
        system.debug('++++++++'+c);
        system.debug('*************SalesHeaderTestMethod Executed Successfully');
    }
    
    




}